"""SqliteSemanticStore — durable backing for the semantic layer (★④).

Drop-in replacement for the in-memory :class:`~lang2sql.semantic.store.SemanticStore`:
same ``add(scope, entry)`` / ``entries_at(scope)`` surface, but rows live in a
stdlib :mod:`sqlite3` table so definitions survive a process restart. Wiring
``ScopeResolver(store=SqliteSemanticStore(path))`` is all federation needs to
become persistent — the resolver and merge logic stay untouched.

Like the rest of V1's sqlite usage this is synchronous and inline; the store
itself exposes the plain ``add``/``entries_at`` shape (no ``async``), matching
:class:`SemanticStore` so it substitutes cleanly under :class:`ScopeResolver`.
"""

from __future__ import annotations

import sqlite3

from ...core.identity import Scope
from ...semantic.types import SemanticEntry, SemanticKind


class SqliteSemanticStore:
    """Per-scope semantic entries persisted in a single sqlite table.

    The ``(scope, name)`` pair is the primary key, mirroring the in-memory
    store's "one entry per name within a scope" rule: re-adding a name at the
    same scope replaces the prior definition.
    """

    def __init__(self, path: str = ":memory:") -> None:
        self.path = path
        self._conn = sqlite3.connect(path, check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        self._create_tables()

    def _create_tables(self) -> None:
        self._conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS semantic_entries (
                scope      TEXT NOT NULL,
                kind       TEXT NOT NULL,
                name       TEXT NOT NULL,
                definition TEXT NOT NULL,
                applies_to TEXT NOT NULL DEFAULT '',
                source_id  TEXT NOT NULL DEFAULT '',
                created_by TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL DEFAULT '',
                PRIMARY KEY (scope, name)
            );
            """
        )
        self._conn.commit()

    def close(self) -> None:
        self._conn.close()

    def add(self, scope: Scope, entry: SemanticEntry) -> None:
        """Store ``entry`` at ``scope``, replacing a same-named entry there."""
        self._conn.execute(
            "INSERT INTO semantic_entries "
            "(scope, kind, name, definition, applies_to, source_id, created_by, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(scope, name) DO UPDATE SET "
            "kind = excluded.kind, definition = excluded.definition, "
            "applies_to = excluded.applies_to, source_id = excluded.source_id, "
            "created_by = excluded.created_by, created_at = excluded.created_at",
            (
                str(scope),
                entry.kind.value,
                entry.name,
                entry.definition,
                entry.applies_to,
                entry.source_id,
                entry.created_by,
                entry.created_at,
            ),
        )
        self._conn.commit()

    def entries_at(self, scope: Scope) -> list[SemanticEntry]:
        """Entries authored exactly at ``scope`` (no inheritance)."""
        rows = self._conn.execute(
            "SELECT kind, name, definition, applies_to, source_id, created_by, created_at "
            "FROM semantic_entries WHERE scope = ? ORDER BY rowid",
            (str(scope),),
        ).fetchall()
        return [_row_to_entry(r) for r in rows]


def _row_to_entry(row: sqlite3.Row) -> SemanticEntry:
    """Reconstruct a :class:`SemanticEntry` from a stored row.

    ``created_at`` is passed through verbatim so the persisted timestamp is
    preserved rather than regenerated by ``__post_init__``.
    """
    return SemanticEntry(
        kind=SemanticKind(row["kind"]),
        name=row["name"],
        definition=row["definition"],
        applies_to=row["applies_to"],
        source_id=row["source_id"],
        created_by=row["created_by"],
        created_at=row["created_at"],
    )
